"""Generate voice prompt PCM C arrays using Windows SAPI TTS (pyttsx3).
No external dependencies beyond pyttsx3 + standard library.
"""
import os
import sys
import struct
import wave
import tempfile
import pyttsx3

PROMPTS = [
    ("one",   "one"),
    ("two",   "two"),
    ("three", "three"),
    ("four",  "four"),
    ("five",  "five"),
    ("six",   "six"),
]

TARGET_RATE = 16000
OUTPUT_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                           "peripheral_server_sleep", "code", "vp_pcm_data.c")


def resample_pcm(samples: list, src_rate: int, dst_rate: int) -> list:
    """Simple linear interpolation resampling. src->dst rate conversion."""
    if src_rate == dst_rate:
        return samples
    ratio = src_rate / dst_rate
    out_len = int(len(samples) / ratio)
    result = []
    for i in range(out_len):
        src_idx = i * ratio
        src_i = int(src_idx)
        frac = src_idx - src_i
        if src_i + 1 < len(samples):
            val = int(samples[src_i] * (1 - frac) + samples[src_i + 1] * frac)
        else:
            val = samples[src_i]
        result.append(val)
    return result


def apply_telecoil_eq(samples: list, rate: int) -> list:
    """Compensate for Telecoil bandpass (300-3400Hz): bass boost + HF cut."""
    # 1-pole low-pass at 500Hz for bass boost shelf
    lp_a = 0.9  # ~500Hz at 16kHz
    lp_state = 0.0
    boosted = []
    for s in samples:
        lp_state = lp_a * lp_state + (1.0 - lp_a) * s
        # Add 200% of low-passed signal = +9.5dB bass boost
        boosted.append(int(s + 2.0 * lp_state))

    # 1-pole low-pass at 3kHz to reduce harshness
    lp2_a = 0.5  # ~3kHz at 16kHz
    lp2_state = 0.0
    result = []
    for s in boosted:
        lp2_state = lp2_a * lp2_state + (1.0 - lp2_a) * s
        result.append(int(lp2_state))

    # Clamp to 16-bit range
    result = [max(-32768, min(32767, s)) for s in result]
    return result


def generate_pcm(text: str) -> list:
    """Generate 8kHz mono 16-bit PCM from text using Windows SAPI."""
    engine = pyttsx3.init()
    # Set voice to English
    voices = engine.getProperty('voices')
    eng_voice = None
    for v in voices:
        if 'english' in v.name.lower() or 'en' in v.id.lower():
            eng_voice = v.id
            break
    if eng_voice:
        engine.setProperty('voice', eng_voice)
    engine.setProperty('rate', 150)  # slower, better quality

    # Save to temp WAV file
    tmp = tempfile.NamedTemporaryFile(suffix='.wav', delete=False)
    tmp_path = tmp.name
    tmp.close()

    engine.save_to_file(text, tmp_path)
    engine.runAndWait()

    # Read WAV and convert to samples
    with wave.open(tmp_path, 'rb') as wf:
        n_frames = wf.getnframes()
        src_rate = wf.getframerate()
        raw = wf.readframes(n_frames)

    os.unlink(tmp_path)

    # Parse 16-bit PCM
    samples = []
    for i in range(0, len(raw), 2):
        val = struct.unpack_from('<h', raw, i)[0]
        samples.append(val)

    # Resample to 8kHz if needed
    if src_rate != TARGET_RATE:
        samples = resample_pcm(samples, src_rate, TARGET_RATE)

    # Trim leading/trailing silence
    trim_thresh = 300
    start = 0
    while start < len(samples) and abs(samples[start]) < trim_thresh:
        start += 1
    end = len(samples) - 1
    while end > start and abs(samples[end]) < trim_thresh:
        end -= 1
    # Keep a small margin
    margin = TARGET_RATE // 100  # 10ms
    samples = samples[max(0, start - margin):min(len(samples), end + margin)]

    return samples


def format_c_array(name: str, samples: list) -> str:
    """Format int16 list as a C const array."""
    lines = [f"static const int16_t {name}[] = {{"]
    for i in range(0, len(samples), 12):
        row = ", ".join(str(s) for s in samples[i:i + 12])
        lines.append(f"    {row},")
    lines.append("};")
    return "\n".join(lines)


def main():
    print("Generating voice prompts with Windows SAPI (pyttsx3)...")
    arrays = {}

    for var_name, text in PROMPTS:
        print(f"  Generating: '{text}' -> {var_name}")
        samples = generate_pcm(text)
        samples = apply_telecoil_eq(samples, TARGET_RATE)
        arrays[var_name] = samples
        duration_ms = len(samples) * 1000 // TARGET_RATE
        print(f"    -> {len(samples)} samples, {duration_ms}ms, {len(samples)*2} bytes flash")

    # Build C file
    lines = []
    lines.append("/* Auto-generated by scripts/gen_voice_prompts.py — DO NOT EDIT */")
    lines.append('#include "voice_prompt.h"')
    lines.append("")

    for var_name, _ in PROMPTS:
        lines.append(format_c_array(f"vp_pcm_{var_name}", arrays[var_name]))
        lines.append("")

    lines.append("const vp_prompt_t vp_prompts[VP_PROMPT_COUNT] = {")
    for idx, (var_name, _) in enumerate(PROMPTS):
        arr = arrays[var_name]
        lines.append(f"    [{idx}] = {{ vp_pcm_{var_name}, {len(arr)} }},")
    lines.append("};")

    content = "\n".join(lines)

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(content)

    total_bytes = sum(len(a) * 2 for a in arrays.values())
    print(f"\nDone! Output: {OUTPUT_FILE}")
    print(f"Total flash: {total_bytes} bytes ({total_bytes/1024:.1f} KB)")
    print(f"Total duration: {sum(len(a)/TARGET_RATE for a in arrays.values()):.1f}s")


if __name__ == "__main__":
    main()
